// Enum is non-exhaustive, codes are from the BLS API documentation at:
// https://download.bls.gov/pub/time.series/cu/cu.area
export enum AreaCodes {
	UsCityAverage = '0000',
	Northeast = '0100',
	NewEngland = '0110',
	MiddleAtlantic = '0120',
	Midwest0 = '0200',
	EastNorthCentral = '0230',
	WestNorthCentral = '0240',
	South0 = '0300',
	SouthAtlantic = '0350',
	EastSouthCentral = '0360',
	WestSouthCentral = '0370',
	West0 = '0400',
	Mountain = '0480',
	Pacific = '0490',
	PittsburghPa = 'A104',
	ClevelandAkronOh = 'A210',
	MilwaukeeRacineWi = 'A212',
	CincinnatiHamiltonOhKyIn = 'A213',
	KansasCityMoKs = 'A214',
	WashingtonBaltimoreDcMdVaWv = 'A311',
	LosAngelesRiversideOrangeCountyCa = 'A421',
	PortlandSalemOrWa = 'A425',
	BostonCambridgeNewtonMaNh = 'S11A',
	NewYorkNewarkJerseyCityNyNjPa = 'S12A',
	PhiladelphiaCamdenWilmingtonPaNjDeMd = 'S12B',
	ChicagoNapervilleElginIlInWi = 'S23A',
	DetroitWarrenDearbornMi = 'S23B',
	MinneapolisStPaulBloomingtonMnWi = 'S24A',
	StLouisMoIl = 'S24B',
	WashingtonArlingtonAlexandriaDcVaMdWv = 'S35A',
	MiamiFortLauderdaleWestPalmBeachFl = 'S35B',
	AtlantaSandySpringsRoswellGa = 'S35C',
	TampaStPetersburgClearwaterFl = 'S35D',
	BaltimoreColumbiaTowsonMd = 'S35E',
	DallasFortWorthArlingtonTx = 'S37A',
	HoustonTheWoodlandsSugarLandTx = 'S37B',
	PhoenixMesaScottsdaleAz = 'S48A',
	DenverAuroraLakewoodCo = 'S48B',
	LosAngelesLongBeachAnaheimCa = 'S49A',
	SanFranciscoOaklandHaywardCa = 'S49B',
	RiversideSanBernardinoOntarioCa = 'S49C',
	SeattleTacomaBellevueWa = 'S49D',
	SanDiegoCarlsbadCa = 'S49E',
	UrbanHawaii = 'S49F',
	UrbanAlaska = 'S49G',
}

// Enum is non-exhaustive, codes are from the BLS API documentation at:
// https://download.bls.gov/pub/time.series/cu/cu.item
export enum CpiItemCodes {
	AllItems = 'SA0',
	PurchasingPowerOfTheConsumerDollar = 'SA0R',
	MensAndBoysApparel = 'SAA1',
	WomensAndGirlsApparel = 'SAA2',
	Commodities = 'SAC',
	EnergyCommodities = 'SACE',
	FoodAndBeverages = 'SAF',
	Food = 'SAF1',
	Housing = 'SAH',
	Shelter = 'SAH1',
	FuelsAndUtilities = 'SAH2',
	HouseholdEnergy = 'SAH21',
	MedicalCare = 'SAM',
	JewelryAndWatches = 'SEAG',
	Jewelry = 'SEAG01',
	Watches = 'SEAG02',
	Coffee = 'SEFP01',
}

// This should be exhaustive, but not totally certain
// https://www.bls.gov/help/def/cu.htm
export enum Periodicity {
	Monthly = 'R',
	SemiAnnual = 'S',
}
